language: node_js
node_js:
  - "0.12"
  - "4.4"
branches:
  only:
    - master
    - dev
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install --quiet -g gulp bower karma eslint

script: gulp

after_success:
  - bash <(curl -s https://codecov.io/bash)
